// Auth Types
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

// Alert Types
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// Wishlist Types
export const GET_WISHLISTS = 'GET_WISHLISTS';
export const GET_WISHLIST = 'GET_WISHLIST';
export const CREATE_WISHLIST = 'CREATE_WISHLIST';
export const UPDATE_WISHLIST = 'UPDATE_WISHLIST';
export const DELETE_WISHLIST = 'DELETE_WISHLIST';
export const ADD_WISHLIST_ITEM = 'ADD_WISHLIST_ITEM';
export const UPDATE_WISHLIST_ITEM = 'UPDATE_WISHLIST_ITEM';
export const DELETE_WISHLIST_ITEM = 'DELETE_WISHLIST_ITEM';
export const WISHLIST_ERROR = 'WISHLIST_ERROR';
export const CLEAR_WISHLIST = 'CLEAR_WISHLIST';

// Donation Types
export const GET_DONATIONS = 'GET_DONATIONS';
export const GET_DONATION = 'GET_DONATION';
export const CREATE_DONATION = 'CREATE_DONATION';
export const UPDATE_DONATION_STATUS = 'UPDATE_DONATION_STATUS';
export const DONATION_ERROR = 'DONATION_ERROR';
export const CLEAR_DONATION = 'CLEAR_DONATION';

// Feed Types
export const GET_POPULAR_WISHLISTS = 'GET_POPULAR_WISHLISTS';
export const GET_NEW_WISHLISTS = 'GET_NEW_WISHLISTS';
export const GET_CATEGORY_WISHLISTS = 'GET_CATEGORY_WISHLISTS';
export const SEARCH_WISHLISTS = 'SEARCH_WISHLISTS';
export const FEED_ERROR = 'FEED_ERROR';
export const CLEAR_FEED = 'CLEAR_FEED';

// Profile Types
export const GET_PROFILE = 'GET_PROFILE';
export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const GET_RECEIVED_DONATIONS = 'GET_RECEIVED_DONATIONS';
export const GET_SENT_DONATIONS = 'GET_SENT_DONATIONS';
export const GET_BALANCE = 'GET_BALANCE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';